package com.daroch.payment.controllers;

import com.daroch.payment.dto.ErrorResponse;
import com.daroch.payment.exceptions.BusinessException;
import com.daroch.payment.exceptions.ForbiddenException;
import com.daroch.payment.exceptions.ValidationException;
import com.daroch.payment.logs.LogEvent;
import com.daroch.payment.logs.LogEventFactory;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.ConstraintViolationException;
import java.time.Instant;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.web.HttpRequestMethodNotSupportedException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.servlet.resource.NoResourceFoundException;

@RestControllerAdvice
@Slf4j
@RequiredArgsConstructor
public class GlobalExceptionHandler {

  private final LogEventFactory logEventFactory;
  private final ObjectMapper objectMapper;

  /**
   * Handles validation failures raised by custom application validation.
   *
   * <p>Used for domain-specific validation rules that are not covered by bean validation
   * annotations.
   *
   * @param ex the validation exception
   * @param request the current HTTP request
   * @return standardized validation error response
   */
  @ExceptionHandler(ValidationException.class)
  public ResponseEntity<ErrorResponse> handleValidationException(
      ValidationException ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(ex.getStatus().value())
            .errorCode(ex.getErrorCode())
            .message(ex.getMessage())
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.status(ex.getStatus()).body(response);
  }

  /**
   * Handles business rule violations.
   *
   * <p>These exceptions indicate that the request is syntactically valid but violates
   * application-specific business constraints.
   *
   * @param ex the business exception
   * @param request the current HTTP request
   * @return standardized business error response
   */
  @ExceptionHandler(BusinessException.class)
  public ResponseEntity<ErrorResponse> handleBusinessException(
      BusinessException ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(ex.getStatus().value())
            .errorCode(ex.getErrorCode())
            .message(ex.getMessage())
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.status(ex.getStatus()).body(response);
  }

  /**
   * Handles bean validation failures triggered by @Valid.
   *
   * <p>Extracts the first validation error and returns it in a standardized error response.
   *
   * @param ex the validation exception generated by Spring
   * @param request the current HTTP request
   * @return standardized validation error response
   */
  @ExceptionHandler(MethodArgumentNotValidException.class)
  public ResponseEntity<ErrorResponse> handleMethodArgumentNotValidException(
      MethodArgumentNotValidException ex, HttpServletRequest request) {

    String errorMessage =
        ex.getBindingResult().getFieldErrors().stream()
            .findFirst()
            .map(error -> error.getField() + ": " + error.getDefaultMessage())
            .orElse("Validation failed");

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.BAD_REQUEST.value())
            .errorCode("VALIDATION_ERROR")
            .message(errorMessage)
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.badRequest().body(response);
  }

  /**
   * Handles forbiddenaccess attempts.
   *
   * <p>This exception is thrown when a user attempts to perform an action without the required
   * permissions or ownership of the requested resource.
   *
   * @param ex the forbidden exception
   * @param request the current HTTP request
   * @return standardized Forbidden error response
   */
  @ExceptionHandler(ForbiddenException.class)
  public ResponseEntity<ErrorResponse> handleUnauthorizedException(
      ForbiddenException ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.FORBIDDEN.value())
            .errorCode("FORBIDDEN_REQUEST")
            .message(ex.getMessage())
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.status(HttpStatus.FORBIDDEN).body(response);
  }

  /**
   * Handles validation failures for request parameters, path variables, and other constraint-based
   * validations.
   *
   * <p>Extracts the first constraint violation and returns it in a standardized error response.
   *
   * @param ex the constraint violation exception
   * @param request the current HTTP request
   * @return standardized validation error response
   */
  @ExceptionHandler(ConstraintViolationException.class)
  public ResponseEntity<ErrorResponse> handleConstraintViolation(
      ConstraintViolationException ex, HttpServletRequest request) {

    String errorMessage =
        ex.getConstraintViolations().stream()
            .findFirst()
            .map(v -> v.getPropertyPath() + ": " + v.getMessage())
            .orElse("Constraint violation occurred");

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.BAD_REQUEST.value())
            .errorCode("CONSTRAINT_VIOLATION")
            .message(errorMessage)
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.badRequest().body(response);
  }

  @ExceptionHandler(HttpRequestMethodNotSupportedException.class)
  public ResponseEntity<ErrorResponse> handleHttpRequestMethodNotSupportedException(
      HttpMessageNotReadableException ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.BAD_REQUEST.value())
            .errorCode("INVALID_REQUEST_METHOD")
            .message("HTTP request method doesnot exist")
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.badRequest().body(response);
  }

  @ExceptionHandler(HttpMessageNotReadableException.class)
  public ResponseEntity<ErrorResponse> handleHttpMessageNotReadable(
      HttpMessageNotReadableException ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.BAD_REQUEST.value())
            .errorCode("INVALID_REQUEST_BODY")
            .message("Malformed JSON request")
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.badRequest().body(response);
  }

  /**
   * Handles requests targeting endpoints that do not exist.
   *
   * <p>Returns a standardized 404 response instead of exposing framework-specific error details.
   *
   * @param ex the resource not found exception
   * @param request the current HTTP request
   * @return standardized error response with HTTP 404 status
   */
  @ExceptionHandler(NoResourceFoundException.class)
  public ResponseEntity<ErrorResponse> handleNoResourceFoundException(
      NoResourceFoundException ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.NOT_FOUND.value())
            .errorCode("ENDPOINT_NOT_FOUND")
            .message("Endpoint not found")
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.warn(response, ex));

    return ResponseEntity.status(HttpStatus.NOT_FOUND).body(response);
  }

  /**
   * Handles any unexpected exception that is not explicitly caught by another exception handler.
   *
   * <p>Returns a generic 500 Internal Server Error response to avoid exposing implementation
   * details to clients while ensuring the failure is captured in structured application logs.
   *
   * @param ex the unexpected exception
   * @param request the current HTTP request
   * @return standardized error response with HTTP 500 status
   */
  @ExceptionHandler(Exception.class)
  public ResponseEntity<ErrorResponse> handleException(Exception ex, HttpServletRequest request) {

    ErrorResponse response =
        ErrorResponse.builder()
            .timestamp(Instant.now())
            .status(HttpStatus.INTERNAL_SERVER_ERROR.value())
            .errorCode("INTERNAL_SERVER_ERROR")
            .message("An unexpected error occurred")
            .path(request.getRequestURI())
            .build();

    log(logEventFactory.error(response, ex));
    log.error("----- somthing fuckedup real bad -----", ex);

    return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(response);
  }

  /**
   * Serializes a {@link LogEvent} into JSON and writes it using the appropriate log level.
   *
   * <p>The log level defined within the {@code LogEvent} determines which SLF4J logging method is
   * invoked (INFO, WARN, ERROR, DEBUG, or TRACE).
   *
   * <p>If serialization fails, a fallback error message is written to prevent the original logging
   * operation from disrupting request processing.
   *
   * @param logEvent the structured log event to serialize and write
   */
  private void log(LogEvent logEvent) {
    try {
      String json = objectMapper.writeValueAsString(logEvent);

      switch (logEvent.getLevel()) {
        case INFO -> log.info(json);
        case WARN -> log.warn(json);
        case ERROR -> log.error(json);
        case DEBUG -> log.debug(json);
        case TRACE -> log.trace(json);
      }

    } catch (JsonProcessingException ex) {
      log.error("Failed to serialize LogEvent", ex);
    }
  }
}
